# The key value pairs found below are available within the templates.
# {{site_name}}, {{url}}, {{copyright}} and {{analytics_code}}

:site_name: K. Muncie
:url: http://kmuncie.com
:domain: kmuncie.com
:copyright: 2013
:analytics_code: UA-00000000-0